-- Table: public.shot_records
DROP TABLE IF EXISTS public."shot_records";
CREATE TABLE IF NOT EXISTS public."shot_records" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) NOT NULL,
"shot_id" INTEGER  NOT NULL,
"session_id" INTEGER  NOT NULL,
"shot_number" INTEGER  NOT NULL,
"timestamp_ms" INTEGER  NOT NULL,
"split_time_ms" TEXT,
"target_zone_hit" TEXT,
"x_impact_cm" TEXT,
"y_impact_cm" TEXT,
"muzzle_velocity_fps" TEXT,
"trigger_pull_weight_lbs" TEXT,
"environmental_adjust" TEXT,
"hit_outcome" TEXT
);
TABLESPACE pg_default;

ALTER TABLE public."shot_records" ADD CONSTRAINT "PK_shotRecords" PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS "IX_shotRecords_shot_id" ON public."shot_records" ("shot_id");

CREATE INDEX IF NOT EXISTS "IX_shotRecords_session_id" ON public."shot_records" ("session_id");

CREATE INDEX IF NOT EXISTS "IX_shotRecords_timestamp_ms" ON public."shot_records" ("timestamp_ms");

