-- Table: public.shot_records
-- Spatial columns use PostGIS GEOMETRY with SRID 4326
DROP TABLE IF EXISTS public."shot_records";
CREATE TABLE IF NOT EXISTS public."shot_records" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"shot_id" INTEGER  NOT NULL,
"session_id" INTEGER  NOT NULL,
"shot_number" INTEGER  NOT NULL,
"timestamp_ms" INTEGER  NOT NULL,
"shooter_position" GEOMETRY(GEOMETRY, 4326)  NOT NULL,
"target_position" GEOMETRY(GEOMETRY, 4326),
"impact_point" GEOMETRY(GEOMETRY, 4326),
"trajectory" GEOMETRY(GEOMETRY, 4326),
"distance_meters" TEXT,
"muzzle_velocity_fps" TEXT,
"hit_outcome" TEXT,
"target_zone_hit" TEXT
);
TABLESPACE pg_default;

ALTER TABLE public."shot_records" ADD CONSTRAINT "PK_shot_records" PRIMARY KEY (id);

