-- Table: public.trainees
DROP TABLE IF EXISTS public."trainees";
CREATE TABLE IF NOT EXISTS public."trainees" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) NOT NULL,
"trainee_id" INTEGER  NOT NULL,
"badge_number" TEXT,
"last_name" TEXT,
"first_name" TEXT,
"agency" TEXT,
"unit" TEXT,
"clearance_level" TEXT,
"weapon_qualifications" TEXT,
"total_rounds_fired" TEXT,
"career_hit_percentage" TEXT,
"observer_notes" TEXT
);
TABLESPACE pg_default;

ALTER TABLE public."trainees" ADD CONSTRAINT "PK_trainees" PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS "IX_trainees_trainee_id" ON public."trainees" ("trainee_id");

