-- Table: public.training_sessions
-- Spatial columns use PostGIS GEOMETRY with SRID 4326
DROP TABLE IF EXISTS public."training_sessions";
CREATE TABLE IF NOT EXISTS public."training_sessions" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"session_id" INTEGER  NOT NULL,
"scenario_id" INTEGER  NOT NULL,
"trainee_id" INTEGER  NOT NULL,
"weapon_id" TEXT,
"lane_number" TEXT,
"start_timestamp" TIMESTAMP WITH TIME ZONE  NOT NULL,
"end_timestamp" TEXT,
"firing_position_start" GEOMETRY(GEOMETRY, 4326),
"session_path" GEOMETRY(GEOMETRY, 4326),
"total_shots" TEXT,
"hits" TEXT,
"hit_percentage" TEXT,
"score" TEXT,
"qualification_achieved" TEXT,
"aar_summary" TEXT
);
TABLESPACE pg_default;

ALTER TABLE public."training_sessions" ADD CONSTRAINT "PK_training_sessions" PRIMARY KEY (id);

