-- Table: public.training_sessions
DROP TABLE IF EXISTS public."training_sessions";
CREATE TABLE IF NOT EXISTS public."training_sessions" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) NOT NULL,
"session_id" INTEGER  NOT NULL,
"scenario_id" INTEGER  NOT NULL,
"trainee_id" INTEGER  NOT NULL,
"weapon_id" TEXT,
"lane_number" TEXT,
"start_timestamp" TIMESTAMP WITH TIME ZONE  NOT NULL,
"end_timestamp" TEXT,
"total_shots" TEXT,
"hits" TEXT,
"hit_percentage" TEXT,
"score" TEXT,
"qualification_achieved" TEXT,
"instructor_notes" TEXT,
"video_recording_url" TEXT,
"aar_summary" TEXT,
"vulnerability_model" TEXT
);
TABLESPACE pg_default;

ALTER TABLE public."training_sessions" ADD CONSTRAINT "PK_trainingSessions" PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS "IX_trainingSessions_session_id" ON public."training_sessions" ("session_id");

CREATE INDEX IF NOT EXISTS "IX_trainingSessions_scenario_id" ON public."training_sessions" ("scenario_id");

CREATE INDEX IF NOT EXISTS "IX_trainingSessions_trainee_id" ON public."training_sessions" ("trainee_id");

CREATE INDEX IF NOT EXISTS "IX_trainingSessions_weapon_id" ON public."training_sessions" ("weapon_id");

CREATE INDEX IF NOT EXISTS "IX_trainingSessions_start_timestamp" ON public."training_sessions" ("start_timestamp");

CREATE INDEX IF NOT EXISTS "IX_trainingSessions_end_timestamp" ON public."training_sessions" ("end_timestamp");

