-- Table: public.trainees
-- Spatial columns use PostGIS GEOMETRY with SRID 4326
DROP TABLE IF EXISTS public."trainees";
CREATE TABLE IF NOT EXISTS public."trainees" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"trainee_id" INTEGER,
"badge_number" TEXT,
"last_name" TEXT,
"first_name" TEXT,
"agency" TEXT,
"unit" TEXT,
"home_base_location" GEOMETRY(GEOMETRY, 4326)
);
TABLESPACE pg_default;

ALTER TABLE public."trainees" ADD CONSTRAINT "PK_trainees" PRIMARY KEY (id);

