-- Table: public.weapon_training_scenarios
DROP TABLE IF EXISTS public."weapon_training_scenarios";
CREATE TABLE IF NOT EXISTS public."weapon_training_scenarios" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) NOT NULL,
"scenario_id" INTEGER  NOT NULL,
"scenario_code" TEXT,
"title" TEXT,
"weapon_category" TEXT,
"qualification_course" TEXT,
"difficulty_level" TEXT,
"time_limit_seconds" TEXT,
"required_hits" TEXT,
"max_rounds" TEXT,
"target_configuration" TEXT,
"environmental_factors" TEXT,
"classification" TEXT,
"is_active" BOOLEAN
);
TABLESPACE pg_default;

ALTER TABLE public."weapon_training_scenarios" ADD CONSTRAINT "PK_weaponTrainingScenarios" PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS "IX_weaponTrainingScenarios_scenario_id" ON public."weapon_training_scenarios" ("scenario_id");

