-- Table: public.weapon_inventory
-- Spatial columns use PostGIS GEOMETRY with SRID 4326
DROP TABLE IF EXISTS public."weapon_inventory";
CREATE TABLE IF NOT EXISTS public."weapon_inventory" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"weapon_id" INTEGER  NOT NULL,
"serial_number" TEXT,
"make" TEXT,
"model" TEXT,
"caliber" TEXT,
"weapon_type" TEXT,
"barrel_length_in" TEXT,
"sights" TEXT,
"assigned_to_trainee_id" TEXT,
"status" TEXT,
"simulation_mode" TEXT
);

ALTER TABLE public."weapon_inventory" ADD CONSTRAINT "PK_weapon_inventory" PRIMARY KEY (id);

