-- Table: public.weapon_inventory
DROP TABLE IF EXISTS public."weapon_inventory";
CREATE TABLE IF NOT EXISTS public."weapon_inventory" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) NOT NULL,
"weapon_id" INTEGER  NOT NULL,
"serial_number" TEXT,
"make" TEXT,
"model" TEXT,
"caliber" TEXT,
"weapon_type" TEXT,
"barrel_length_in" TEXT,
"sights" TEXT,
"assigned_to_trainee_id" TEXT,
"status" TEXT,
"simulation_mode" TEXT
);
TABLESPACE pg_default;

ALTER TABLE public."weapon_inventory" ADD CONSTRAINT "PK_weaponInventory" PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS "IX_weaponInventory_weapon_id" ON public."weapon_inventory" ("weapon_id");

CREATE INDEX IF NOT EXISTS "IX_weaponInventory_assigned_to_trainee_id" ON public."weapon_inventory" ("assigned_to_trainee_id");

