-- Table: public.weapon_training_scenarios
-- Spatial columns use PostGIS GEOMETRY with SRID 4326
DROP TABLE IF EXISTS public."weapon_training_scenarios";
CREATE TABLE IF NOT EXISTS public."weapon_training_scenarios" (
"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
"scenario_id" INTEGER  NOT NULL,
"scenario_code" TEXT,
"title" TEXT,
"weapon_category" TEXT,
"difficulty_level" TEXT,
"time_limit_seconds" TEXT,
"exercise_boundary" GEOMETRY(GEOMETRY, 4326),
"target_zones" TEXT,
"environmental_factors" TEXT,
"classification" TEXT
);

ALTER TABLE public."weapon_training_scenarios" ADD CONSTRAINT "PK_weapon_training_scenarios" PRIMARY KEY (id);

